#!/usr/bin/env bash
set -euo pipefail

# create-templates.sh
# Creates/overwrites NON-MD template files under:
#   ${HOME}/Projects/Scripts/Templates/
#     provision.sh
#     supabase.config.json
#     sql/bootstrap.sql
#     sql/seed.sql
#
# NOTE: PROVISION.md is intentionally NOT created here (you have it in Canvas).

ROOT="${HOME}/Projects/Scripts"
TPL="${ROOT}/Templates"

mkdir -p "${TPL}/sql"

write() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  cat > "$path"
}

chmod +x "${TPL}/provision.sh" 2>/dev/null || true

echo "[create-templates] Writing: ${TPL}/supabase.config.json"
write "${TPL}/supabase.config.json" <<'EOF'
{
  "project": {
    "name": "__PROJECT_NAME__",
    "org_slug": "__SUPABASE_ORG_SLUG__",
    "provider": "__SUPABASE_PROVIDER__",
    "region": "__SUPABASE_REGION__"
  }
}
EOF

echo "[create-templates] Writing: ${TPL}/sql/bootstrap.sql"
write "${TPL}/sql/bootstrap.sql" <<'EOF'
create table if not exists public.healthcheck (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);
EOF

echo "[create-templates] Writing: ${TPL}/sql/seed.sql"
write "${TPL}/sql/seed.sql" <<'EOF'
-- keep seed idempotent-ish; identity column will be generated
insert into public.healthcheck default values;
EOF

echo "[create-templates] Writing: ${TPL}/provision.sh"
write "${TPL}/provision.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

# provision.sh (template)
# - Netlify: ensure auth, create/link site if needed, import .env
# - Supabase: ensure auth, link or optionally create project, write env vars to .env
# - Optional: apply schema+seed via Supabase CLI if supported
#
# Safe to re-run.

log() { printf '%s\n' "[provision] $*"; }
die() { printf '%s\n' "[provision] ERROR: $*" >&2; exit 1; }
need_cmd() { command -v "$1" >/dev/null 2>&1 || die "Missing command: $1"; }

SB_CREATE="false"
APPLY_SCHEMA="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --sb-create) SB_CREATE="true"; shift ;;
    --apply-schema) APPLY_SCHEMA="true"; shift ;;
    -h|--help)
      cat <<'TXT'
Usage: ./scripts/provision.sh [--sb-create] [--apply-schema]

--sb-create     Attempt to create a Supabase project using supabase.config.json (best-effort)
--apply-schema  Apply sql/bootstrap.sql and sql/seed.sql (best-effort)

Netlify is always linked and .env is always imported.
TXT
      exit 0
      ;;
    *) break ;;
  esac
done

# run from project root even if invoked from scripts/
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "${SCRIPT_DIR}/../.scaffold/meta.json" ]]; then
  cd "${SCRIPT_DIR}/.."
elif [[ -f "${SCRIPT_DIR}/.scaffold/meta.json" ]]; then
  cd "${SCRIPT_DIR}"
else
  die "Cannot find .scaffold/meta.json. Run from the scaffolded project."
fi

read_json() {
  local file="$1" expr="$2"
  node -e "const fs=require('fs');const j=JSON.parse(fs.readFileSync('$file','utf8'));const v=$expr;process.stdout.write(v==null?'':String(v));"
}

# Cross-platform .env update via Node (no sed -i differences)
set_env_kv() {
  local key="$1" value="$2"
  [[ -f ".env" ]] || touch ".env"
  node - <<EOF_NODE
const fs = require("fs");
const p = ".env";
const key = ${key@Q};
const val = ${value@Q};
let s = fs.readFileSync(p, "utf8");
let lines = s.split(/\r?\n/);
let found = false;
lines = lines.map(line => {
  if (line.startsWith(key + "=")) { found = true; return key + "=" + val; }
  return line;
});
if (!found) lines.push(key + "=" + val);
fs.writeFileSync(p, lines.join("\n").replace(/\n{3,}/g,"\n\n").trimEnd() + "\n");
EOF_NODE
}

ensure_netlify_auth() {
  local cfg="$HOME/.config/netlify/config.json"
  [[ -f "$cfg" ]] || die "Netlify config not found at $cfg. Run: netlify login"

  # Support both top-level token and nested users[userId].auth.token (your setup)
  local token
  token="$(
    node -e "
      const fs=require('fs');
      const j=JSON.parse(fs.readFileSync('${cfg}','utf8'));

      if (typeof j.token==='string' && j.token.trim()) { process.stdout.write(j.token.trim()); process.exit(0); }

      const uid=String(j.userId||'');
      if (uid && j.users && j.users[uid] && j.users[uid].auth && typeof j.users[uid].auth.token==='string') {
        const t=j.users[uid].auth.token.trim();
        if (t) { process.stdout.write(t); process.exit(0); }
      }

      const users=j.users||{};
      for (const k of Object.keys(users)) {
        const t=users?.[k]?.auth?.token;
        if (typeof t==='string' && t.trim()) { process.stdout.write(t.trim()); process.exit(0); }
      }

      process.exit(1);
    " 2>/dev/null || true
  )"
  [[ -n "$token" ]] || die "Netlify token not found in $cfg. Run: netlify login"
}

ensure_netlify_link() {
  if [[ -f ".netlify/state.json" ]]; then
    log "Netlify already linked (.netlify/state.json present)"
    return
  fi
  local name
  name="$(basename "$(pwd)")"
  log "Creating/linking Netlify site: $name"
  netlify sites:create --name "$name"
}

import_env_to_netlify() {
  [[ -f ".env" ]] || die ".env missing. Copy .env.example -> .env first (or let this script write it)."
  log "Importing .env into Netlify env vars"
  netlify env:import .env
}

try_supabase_create_from_config() {
  [[ -f "supabase.config.json" ]] || die "Missing supabase.config.json"
  local name org region provider

  name="$(read_json supabase.config.json "j.project.name")"
  org="$(read_json supabase.config.json "j.project.org_slug")"
  region="$(read_json supabase.config.json "j.project.region")"
  provider="$(read_json supabase.config.json "j.project.provider")"
  [[ -n "$name" ]] || name="$(basename "$(pwd)")"

  log "Attempting Supabase project create (best-effort)"
  log "Config: name=$name org_slug=$org provider=$provider region=$region"

  set +e
  local out rc
  out="$(supabase projects create "$name" 2>&1)"
  rc=$?
  set -e

  if [[ $rc -ne 0 ]]; then
    log "Supabase project creation failed (may be normal depending on permissions/CLI)."
    printf '%s\n' "$out"
    return 1
  fi

  # Best-effort ref extraction
  printf '%s' "$out" | grep -Eo '[a-z0-9]{16,32}' | head -n 1
}

apply_sql_best_effort() {
  local file="$1"
  [[ -f "$file" ]] || die "Missing SQL file: $file"

  if supabase db query --help >/dev/null 2>&1; then
    log "Applying SQL: $file"
    # shellcheck disable=SC2094
    supabase db query < "$file"
  else
    log "Cannot auto-apply $file (Supabase CLI lacks 'db query')."
    log "Apply manually in Supabase Dashboard -> SQL Editor:"
    log "  $file"
    return 1
  fi
}

prompt_required() {
  local label="$1"
  local v=""
  while [[ -z "$v" ]]; do
    read -rp "$label" v
  done
  printf '%s' "$v"
}

main() {
  need_cmd node
  need_cmd netlify
  need_cmd supabase

  log "Checking toolchain"
  if [[ -f "scripts/check-tools.mjs" ]]; then node scripts/check-tools.mjs || true; fi

  log "Netlify"
  ensure_netlify_auth
  ensure_netlify_link
  import_env_to_netlify

  log "Supabase auth"
  supabase projects list >/dev/null

  local ref="${SUPABASE_PROJECT_REF:-}"
  if [[ -z "$ref" && "$SB_CREATE" == "true" ]]; then
    ref="$(try_supabase_create_from_config || true)"
  fi
  if [[ -z "$ref" ]]; then
    ref="$(prompt_required "Enter SUPABASE_PROJECT_REF (e.g. abcd1234efgh5678): ")"
  fi

  log "Linking Supabase project: $ref"
  supabase link --project-ref "$ref" >/dev/null || true

  # Runtime env values (paste from dashboard)
  local url vite_url anon service
  url="${SUPABASE_URL:-}"; [[ -n "$url" ]] || url="$(prompt_required "SUPABASE_URL (https://xxxx.supabase.co): ")"
  vite_url="${VITE_SUPABASE_URL:-}"; [[ -n "$vite_url" ]] || vite_url="$(prompt_required "VITE_SUPABASE_URL (usually same as SUPABASE_URL): ")"
  anon="${VITE_SUPABASE_ANON_KEY:-}"; [[ -n "$anon" ]] || anon="$(prompt_required "VITE_SUPABASE_ANON_KEY: ")"
  service="${SUPABASE_SERVICE_ROLE_KEY:-}"; [[ -n "$service" ]] || service="$(prompt_required "SUPABASE_SERVICE_ROLE_KEY: ")"

  set_env_kv "SUPABASE_URL" "$url"
  set_env_kv "VITE_SUPABASE_URL" "$vite_url"
  set_env_kv "VITE_SUPABASE_ANON_KEY" "$anon"
  set_env_kv "SUPABASE_SERVICE_ROLE_KEY" "$service"

  if [[ "$APPLY_SCHEMA" == "true" ]]; then
    log "Applying schema + seed (best-effort)"
    apply_sql_best_effort "sql/bootstrap.sql" || true
    apply_sql_best_effort "sql/seed.sql" || true
  else
    log "Schema not applied (use --apply-schema)"
  fi

  import_env_to_netlify
  log "Provision complete"
}

main "$@"
EOF

chmod +x "${TPL}/provision.sh"

cat <<EOF

[create-templates] Done.

Created/updated:
  ${TPL}/provision.sh
  ${TPL}/supabase.config.json
  ${TPL}/sql/bootstrap.sql
  ${TPL}/sql/seed.sql

Next:
  - You already have PROVISION.md in Canvas.
  - Next file to create (outside templates) is scaffold.sh that copies these templates and token-replaces.
EOF
