#!/usr/bin/env bash
set -euo pipefail

# Helpful line number on any failure
trap 'echo "[provision] ERROR: failed at line $LINENO" >&2' ERR

CREATE_DB="false"
APPLY_SCHEMA="false"

usage() {
  cat <<'TXT'
Usage: ./scripts/provision.sh [options]

Options:
  --create-db, --sb-create   Create Supabase project (prompts for DB password)
  --apply-schema             Apply SQL schema/seed files (as migrations) to remote
  -h, --help                 Show help

Unknown flags cause an error.
TXT
}

# Strict flag parsing
while [[ $# -gt 0 ]]; do
  case "$1" in
    --create-db|--sb-create) CREATE_DB="true"; shift ;;
    --apply-schema)         APPLY_SCHEMA="true"; shift ;;
    -h|--help)              usage; exit 0 ;;
    --)                     shift; break ;;
    -*)                     echo "[provision] ERROR: Unknown option: $1" >&2; usage >&2; exit 2 ;;
    *)                      echo "[provision] ERROR: Unexpected argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ $# -gt 0 ]]; then
  echo "[provision] ERROR: Unexpected trailing args: $*" >&2
  exit 2
fi

log() { printf '[provision] %s\n' "$*"; }
die() { printf '[provision] ERROR: %s\n' "$*" >&2; exit 1; }
need_cmd() { command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"; }

prompt_secret() {
  local label="$1"
  local v=""
  while [[ -z "$v" ]]; do
    read -srp "$label" v
    echo >&2
  done
  printf '%s' "$v"
}

strip_to_json() {
  # prints from first line beginning with [ or { (tolerates CLI chatter before JSON)
  sed -n '/^[[:space:]]*[\[{]/,$p'
}

# Create .env with URLs only (keys left blank). Never overwrites an existing .env.
ensure_env_file() {
  local ref="$1"
  local env_file=".env"

  if [[ -f "$env_file" ]]; then
    log ".env already exists (not overwriting)"
    return 0
  fi

  log "Creating .env with Supabase URLs (keys left blank)"
  cat > "$env_file" <<EOF
# Generated by provision.sh
# Fill in missing keys from Supabase dashboard → Settings → API

# Supabase (frontend)
VITE_SUPABASE_URL=https://${ref}.supabase.co
VITE_SUPABASE_ANON_KEY=

# Supabase (server / Netlify functions)
SUPABASE_URL=https://${ref}.supabase.co
SUPABASE_SERVICE_ROLE_KEY=
EOF
}

# Replace or add KEY=value in .env (creates key if missing)
set_env_kv() {
  local key="$1"
  local val="$2"
  local file="${3:-.env}"

  [[ -f "$file" ]] || return 1

  if grep -qE "^${key}=" "$file"; then
    sed -i "s|^${key}=.*|${key}=${val}|" "$file"
  else
    printf '%s=%s\n' "$key" "$val" >> "$file"
  fi
}

env_value() {
  local key="$1"
  local file="${2:-.env}"
  [[ -f "$file" ]] || { echo ""; return 0; }
  grep -E "^${key}=" "$file" | tail -n 1 | sed "s/^${key}=//" || true
}

import_env_to_netlify() {
  local site_id="$1"
  [[ -f ".env" ]] || die ".env missing; cannot import to Netlify"
  log "Importing .env into Netlify env vars (siteId=$site_id)"
  NETLIFY_SITE_ID="$site_id" netlify env:import .env
}

resolve_supabase_org_id() {
  local want="$1"
  local out

  out="$(supabase orgs list --output json 2>&1)" || {
    echo "[provision] ERROR: supabase orgs list failed" >&2
    echo "$out" >&2
    return 1
  }

  out="$(strip_to_json <<<"$out")"
  [[ -n "${out//[[:space:]]/}" ]] || {
    echo "[provision] ERROR: supabase orgs list produced no JSON" >&2
    return 1
  }

  WANT="$want" node -e '
const fs = require("fs");
const s = fs.readFileSync(0, "utf8").trim();
let orgs;
try { orgs = JSON.parse(s); } catch (e) {
  console.error("[provision] ERROR: Failed to parse supabase orgs JSON");
  console.error(s.slice(0, 1000));
  process.exit(2);
}
const want = process.env.WANT || "";
const m = orgs.find(o => o && (o.slug === want || o.id === want));
if (!m) {
  console.error(`[provision] ERROR: Org not found for slug/id: ${want}`);
  console.error("[provision] Available orgs:");
  for (const o of orgs) console.error(` - ${o.slug} (${o.id}) ${o.name || ""}`);
  process.exit(3);
}
process.stdout.write(String(m.id || ""));
' <<<"$out"
}

resolve_supabase_project_ref_by_name() {
  local want_name="$1"
  local out

  out="$(supabase projects list --output json 2>&1)" || {
    echo "[provision] ERROR: supabase projects list failed" >&2
    echo "$out" >&2
    return 1
  }

  out="$(strip_to_json <<<"$out")"
  [[ -n "${out//[[:space:]]/}" ]] || return 1

  WANT="$want_name" node -e '
const fs = require("fs");
const s = fs.readFileSync(0, "utf8").trim();
let projects;
try { projects = JSON.parse(s); } catch (e) {
  console.error("[provision] ERROR: Failed to parse supabase projects JSON");
  console.error(s.slice(0, 1000));
  process.exit(2);
}
const want = process.env.WANT || "";
const p = projects.find(p => p && p.name === want);
if (!p) process.exit(3);
process.stdout.write(String(p.ref || p.project_ref || p.id || ""));
' <<<"$out"
}

fetch_supabase_anon_key() {
  local ref="$1"
  local out

  # This may fail depending on CLI permissions/version; treat as optional.
  out="$(supabase secrets list --project-ref "$ref" --output json 2>/dev/null || true)"
  out="$(strip_to_json <<<"$out")"
  [[ -n "${out//[[:space:]]/}" ]] || return 1

  node -e '
const fs = require("fs");
const s = fs.readFileSync(0,"utf8").trim();
let a;
try { a = JSON.parse(s); } catch { process.exit(1); }
const k = a.find(x => x && x.name === "anon_key" && x.value);
if (k) process.stdout.write(String(k.value));
' <<<"$out"
}

post_provision_summary() {
  echo
  echo "===================="
  echo " Provision summary"
  echo "===================="
  echo "Netlify:"
  echo "  siteId: ${SITE_ID:-"(unknown)"}"
  echo "  linked: $( [[ -f .netlify/state.json ]] && echo yes || echo no )"
  echo
  echo "Supabase:"
  echo "  project ref: ${PROJECT_REF:-"(unknown)"}"
  if [[ -n "${PROJECT_REF:-}" ]]; then
    echo "  url: https://${PROJECT_REF}.supabase.co"
  fi
  echo
  echo ".env:"
  echo "  present: $( [[ -f .env ]] && echo yes || echo no )"
  if [[ -f .env ]]; then
    local a s u
    u="$(env_value VITE_SUPABASE_URL .env)"
    a="$(env_value VITE_SUPABASE_ANON_KEY .env)"
    s="$(env_value SUPABASE_SERVICE_ROLE_KEY .env)"
    echo "  VITE_SUPABASE_URL: ${u:-"(missing)"}"
    echo "  VITE_SUPABASE_ANON_KEY: $( [[ -n "$a" ]] && echo set || echo MISSING )"
    echo "  SUPABASE_SERVICE_ROLE_KEY: $( [[ -n "$s" ]] && echo set || echo MISSING )"
  fi
  echo
  echo "Next:"
  echo "  1) If SERVICE_ROLE is missing, copy it from Supabase dashboard → Settings → API"
  echo "  2) Re-import env to Netlify: NETLIFY_SITE_ID=\"$SITE_ID\" netlify env:import .env"
  echo "  3) Run locally: netlify dev"
  echo
}

# -----------------------------
# locate project root
# -----------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/.."

[[ -f ".scaffold/meta.json" ]] || die "Missing .scaffold/meta.json (not a scaffolded project)"

# -----------------------------
# toolchain
# -----------------------------
log "Checking toolchain"
need_cmd node
need_cmd npm
need_cmd git
need_cmd netlify
need_cmd supabase

[[ -f "scripts/check-tools.mjs" ]] && node scripts/check-tools.mjs

# -----------------------------
# Netlify
# -----------------------------
log "Netlify"

PROJECT_NAME="$(basename "$(pwd)")"

if [[ ! -f ".netlify/state.json" ]]; then
  log "Creating Netlify site (and linking folder): $PROJECT_NAME"
  netlify sites:create --name "$PROJECT_NAME"
else
  log "Netlify already linked (.netlify/state.json present)"
fi

SITE_ID="$(node -p "require('./.netlify/state.json').siteId || ''" 2>/dev/null || true)"
[[ -n "$SITE_ID" ]] || die "Cannot determine Netlify siteId"

# -----------------------------
# Supabase
# -----------------------------
DB="$(node -p "require('./.scaffold/meta.json').db || 'none'")"
if [[ "$DB" != "supabase" ]]; then
  log "DB=none: skipping Supabase"
  post_provision_summary
  log "Provision complete"
  exit 0
fi

log "DB=supabase: provisioning Supabase"
[[ -f "supabase.config.json" ]] || die "Missing supabase.config.json"

SB_NAME="$(node -p "require('./supabase.config.json').project.name || ''")"
SB_ORG_SLUG="$(node -p "require('./supabase.config.json').project.org_slug || ''")"
SB_REGION="$(node -p "require('./supabase.config.json').project.region || ''")"

[[ -n "$SB_NAME" ]] || die "supabase.config.json missing project.name"
[[ -n "$SB_ORG_SLUG" ]] || die "supabase.config.json missing project.org_slug"
[[ -n "$SB_REGION" ]] || die "supabase.config.json missing project.region"

log "Supabase config: name=$SB_NAME org_slug=$SB_ORG_SLUG region=$SB_REGION"

log "Resolving Supabase org id for slug=$SB_ORG_SLUG"
ORG_ID="$(resolve_supabase_org_id "$SB_ORG_SLUG")" || die "Could not resolve Supabase org id"
[[ -n "$ORG_ID" ]] || die "Could not resolve Supabase org id"
log "Resolved Supabase org id: $ORG_ID"

if [[ "$CREATE_DB" == "true" ]]; then
  DB_PASS="$(prompt_secret "Enter NEW Supabase DB password (hidden): ")"
  log "Creating Supabase project: $SB_NAME"
  supabase projects create "$SB_NAME" --org-id "$ORG_ID" --region "$SB_REGION" --db-password "$DB_PASS"
fi

log "Resolving Supabase project ref for: $SB_NAME"
PROJECT_REF="$(resolve_supabase_project_ref_by_name "$SB_NAME" || true)"
if [[ -z "$PROJECT_REF" ]]; then
  read -rp "Enter SUPABASE_PROJECT_REF: " PROJECT_REF
fi
[[ -n "$PROJECT_REF" ]] || die "Supabase project ref required"
log "Using Supabase project ref: $PROJECT_REF"

supabase link --project-ref "$PROJECT_REF" >/dev/null 2>&1 || true

# Create .env and refuse to proceed without it (safety)
ensure_env_file "$PROJECT_REF"
[[ -f ".env" ]] || die ".env is required for local dev + Netlify functions. Create it (or let provision create it) and re-run."

# Try to auto-fetch anon key and populate .env if blank
ANON_KEY="$(fetch_supabase_anon_key "$PROJECT_REF" || true)"
if [[ -n "$ANON_KEY" ]]; then
  if [[ -z "$(env_value VITE_SUPABASE_ANON_KEY .env)" ]]; then
    log "Populating VITE_SUPABASE_ANON_KEY in .env"
    set_env_kv "VITE_SUPABASE_ANON_KEY" "$ANON_KEY" ".env"
  fi
else
  log "Could not auto-fetch anon key (ok). Fill VITE_SUPABASE_ANON_KEY manually in .env"
fi

# Auto-import .env into Netlify once we have attempted anon key fetch
import_env_to_netlify "$SITE_ID"

# -----------------------------
# Apply schema via migrations to remote
# -----------------------------
if [[ "$APPLY_SCHEMA" == "true" ]]; then
  if [[ ! -f "supabase/config.toml" ]]; then
    log "Initializing local Supabase project folder (supabase/config.toml)"
    supabase init >/dev/null
  fi

  mkdir -p supabase/migrations

  if [[ -f "sql/bootstrap.sql" ]]; then
    if ! ls supabase/migrations/*_bootstrap.sql >/dev/null 2>&1; then
      ts_boot="$(date -u +%Y%m%d%H%M%S)"
      mig="supabase/migrations/${ts_boot}_bootstrap.sql"
      log "Creating migration: $mig"
      cp sql/bootstrap.sql "$mig"
    else
      log "Bootstrap migration already exists (skipping create)"
    fi
  else
    log "No sql/bootstrap.sql found (skipping)"
  fi

  if [[ -f "sql/seed.sql" ]]; then
    if ! ls supabase/migrations/*_seed.sql >/dev/null 2>&1; then
      ts_seed="$(date -u +%Y%m%d%H%M%S)"
      if [[ "${ts_boot:-}" == "$ts_seed" ]]; then
        sleep 1
        ts_seed="$(date -u +%Y%m%d%H%M%S)"
      fi
      mig="supabase/migrations/${ts_seed}_seed.sql"
      log "Creating seed migration: $mig"
      cp sql/seed.sql "$mig"
    else
      log "Seed migration already exists (skipping)"
    fi
  else
    log "No sql/seed.sql found (skipping)"
  fi

  log "Pushing migrations to remote (linked) database"
  supabase db push --linked --yes
fi

post_provision_summary
log "Provision complete"
